# This is a basic workflow to help you get started with Actions

name: PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: bundle
      - run: bundle install --jobs 4 --retry 3 --deployment
      - run: bundle exec rake
